"""
build_registro_modelo.py — Gera registro_modelo.md, a versão curta da bíblia que o pipeline carrega.

Extrai de registro_akashico.md as seções listadas em SECOES, na ordem, descarta as linhas
que começam com "Nota:" (recados para o autor) e grava registro_modelo.md.

Uso:
    python build_registro_modelo.py <caminho_do_projeto>
"""

import re
import sys
from pathlib import Path

# Prefixos dos títulos a extrair, na ordem em que saem no arquivo gerado.
SECOES = [
    "## 1. ",
    "## 2. ",
    "### 5.8 ",
    "### 9.5 ",
    "## 10. ",
    "### 13.2 ",
    "## 14. ",
]

CABECALHO = [
    "# Akashic Records",
    "",
    "Generated by build_registro_modelo.py from registro_akashico.md. Do not edit by hand.",
    "",
]


def nivel(linha: str) -> int:
    """Retorna o nível do título markdown (1 para '#', 2 para '##'...) ou 0 se não for título."""
    m = re.match(r"^(#+) ", linha)
    return len(m.group(1)) if m else 0


def extrair(linhas: list[str], prefixo: str, source_name: str) -> list[str]:
    """Retorna as linhas da seção cujo título começa com o prefixo, até o próximo título de nível igual ou maior."""
    inicio = next((i for i, l in enumerate(linhas) if l.startswith(prefixo)), None)
    if inicio is None:
        raise SystemExit(f"Seção não encontrada em {source_name}: {prefixo!r}")
    n = nivel(linhas[inicio])
    fim = len(linhas)
    for j in range(inicio + 1, len(linhas)):
        nj = nivel(linhas[j])
        if nj and nj <= n:
            fim = j
            break
    return linhas[inicio:fim]


def main() -> None:
    if len(sys.argv) < 2:
        print("Uso: python build_registro_modelo.py <caminho_do_projeto>")
        sys.exit(1)
        
    project_dir = Path(sys.argv[1]).resolve()
    fonte = project_dir / "registro_akashico.md"
    destino = project_dir / "registro_modelo.md"
    
    if not fonte.exists():
        print(f"Erro: Arquivo fonte não encontrado em {fonte}")
        sys.exit(1)

    linhas = fonte.read_text(encoding="utf-8").splitlines()
    partes = list(CABECALHO)
    for prefixo in SECOES:
        bloco = [l for l in extrair(linhas, prefixo, fonte.name) if not l.startswith("Nota:")]
        partes.extend(bloco)
        partes.append("")
    texto = "\n".join(partes)
    texto = re.sub(r"\n{3,}", "\n\n", texto).rstrip() + "\n"
    destino.write_text(texto, encoding="utf-8")

    chars = len(texto)
    pendentes = texto.count("[A DEFINIR")
    print(f"Gerado {destino.name}: {chars} caracteres, cerca de {chars // 3} tokens em português.")
    if pendentes:
        print(f"Atenção: {pendentes} marcações [A DEFINIR] ainda no texto. Responder antes de gerar capítulos.")


if __name__ == "__main__":
    main()
